### ISSUE TITLE
Add "Shapes" category

### ISSUE THREAD

**Issue by derwinmcgeary** [lewismcgeary/VocabBuilder#102]

**Comment by lewismcgeary** [comment]
Should we choose one colour for shapes to not cause confusion with colours category/words

**Comment by derwinmcgeary** [comment]
There are six basic shapes, seven questions in a quiz. This is #wontfix for the time being.

Basic shapes I know: square, rectangle, circle, oval, triangle, diamond

All hail the Time Being!
