### ISSUE TITLE
Colours category

### ISSUE THREAD

**Issue by derwinmcgeary** [lewismcgeary/VocabBuilder#103]
Icon should perhaps be a rainbow or similar
Colours should be more clearly distinguished

**Comment by lewismcgeary** [comment]
Or a double rainbow

**Comment by lewismcgeary** [comment]
![image](https://cloud.githubusercontent.com/assets/12188996/9007613/e33a5692-378a-11e5-99b2-f7b3b87ff80c.png)

**Comment by lewismcgeary** [comment]
![image](https://cloud.githubusercontent.com/assets/12188996/9007621/f2d63fbc-378a-11e5-9b70-9687e39b2639.png)

**Comment by lewismcgeary** [comment]
![image](https://cloud.githubusercontent.com/assets/12188996/9007636/27a30400-378b-11e5-99fe-00cd7019ef88.png)
