### ISSUE TITLE
Database stuff

### ISSUE THREAD

**Issue by derwinmcgeary** [lewismcgeary/VocabBuilder#3]
- Close database when no longer needed
- Move database access from UI thread

**Comment by lewismcgeary** [comment]
Database closed after use.
accessing still needs improvement to do in background

**Comment by lewismcgeary** [comment]
Initial database check/create on launch is now an AsyncTask.

**Comment by lewismcgeary** [comment]
Selecting from the database needs to be Async. not a problem now, but would be on expanded database

**Comment by derwinmcgeary** [comment]
Done now!
