### ISSUE TITLE
Investigate Play Store issues

### ISSUE THREAD

**Issue by derwinmcgeary** [lewismcgeary/VocabBuilder#36]
Do we need a domain? Do we want a domain? Developer account.

**Comment by lewismcgeary** [comment]
Can you have multiple developer accounts?

-Maybe, but not with same google account

**Comment by lewismcgeary** [comment]
Can you change developer account name

-Yes

**Comment by lewismcgeary** [comment]
does developer account need to be linked to a personal gmail account?

-No

**Comment by lewismcgeary** [comment]
If you provide banking details, is this used to link accounts? ie. would you need a different bank account to open another developer account

**Comment by lewismcgeary** [comment]
do you need a VAT number or other form of tax registration number?

**Comment by lewismcgeary** [comment]
Can the com.whatever.appname stuff be changed later? does it matter?

-The name should be unique. The name may contain uppercase or lowercase letters ('A' through 'Z'), numbers, and underscores ('_'). However, individual package name parts may only start with letters.
To avoid conflicts with other developers, you should use Internet domain ownership as the basis for your package names (in reverse). For example, applications published by Google start with com.google. You should also never use the com.example namespace when publishing your applications.

The package name serves as a unique identifier for the application. It's also the default name for the application process (see the <application> element's process process attribute) and the default task affinity of an activity (see the <activity> element's taskAffinity attribute).

Caution: Once you publish your application, you cannot change the package name. The package name defines your application's identity, so if you change it, then it is considered to be a different application and users of the previous version cannot update to the new version.

NB. users can see this in Google playstore link, and in some device settings sections about app processes

**Comment by lewismcgeary** [comment]
When setting up the account do we need to say if it is partnership, limited company etc? can this be changed later on if so?

-Doesn't seem necessary to set up dev account, but may be when setting up a google merchant account to sell apps/in-app purchases. merchant account doesn't need to be set up straight away
