### ISSUE TITLE
Rotation during preloaded causes crash

### ISSUE THREAD

**Issue by lewismcgeary** [lewismcgeary/VocabBuilder#41]

**Comment by lewismcgeary** [comment]
*preloader

**Comment by derwinmcgeary** [comment]
https://stackoverflow.com/questions/3821423/background-task-progress-dialog-orientation-change-is-there-any-100-working/3821998#3821998

Is this the needed thing?

**Comment by derwinmcgeary** [comment]
I think this is OK, have pushed for a thorough testing!

https://stackoverflow.com/questions/20021803/disable-and-enable-orientation-changes-in-an-activity-in-android-programatically
