### ISSUE TITLE
privacy policy

### ISSUE THREAD

**Issue by derwinmcgeary** [lewismcgeary/VocabBuilder#51]

**Comment by derwinmcgeary** [comment]
possibly from here, if it's free https://www.iubenda.com/en/mobile

thoughts?

**Comment by derwinmcgeary** [comment]
[iubebda](https://iubenda.com) is _not_ free for mobile apps. $27 per country per year

[termsfeed](https://termsfeed.com/generator/new/privacy-policy) is cheaper, but no hosting for the policy.

Or live without since we collect absolutely no user data and the only disadvantage is not being listed in "family-friendly apps" (does anyone go there anyway?)

**Comment by lewismcgeary** [comment]
Rejected for family friendly, unclear why, but to do with privacy policy. Needs to be persistent(?),  and "specifically pertain" to our app. Is gihub.io link not considered persistent, is it because the policy said "Appy Talk" and not "Appy Talk: Russian". Something else?

**Comment by lewismcgeary** [comment]
"When you and your children use Appy Talk, we do not collect any data about you.
Therefore we do not share data with any third parties and do not have your personal data stored anywhere.
The Appy Talk app, once installed, does not send or receive any information over the internet.
Any updates to this privacy policy will be notified here and mentioned on our app store listing page.

If you have any questions regarding you or childs personal data please contact us by email at appytalkteam@gmail.com"

**Comment by derwinmcgeary** [comment]
Accepted!
