### ISSUE TITLE
Image fixes needed

### ISSUE THREAD

**Issue by lewismcgeary** [lewismcgeary/VocabBuilder#63]

**Comment by lewismcgeary** [comment]
Hand/fingers Foot/toes. More distinction

**Comment by lewismcgeary** [comment]
Fingers- pixelly when expanded

**Comment by lewismcgeary** [comment]
Dog-pixelly when expanded

**Comment by lewismcgeary** [comment]
Lion- maybe not quite sharp when expanded

**Comment by lewismcgeary** [comment]
Red- no outline, others have black outline

**Comment by lewismcgeary** [comment]
Carrot - pixelly when expanded

**Comment by lewismcgeary** [comment]
Sandwich- pixelly when expanded

**Comment by lewismcgeary** [comment]
Juice - pixelly

**Comment by lewismcgeary** [comment]
Tomato pixelly

**Comment by lewismcgeary** [comment]
Sweater pixelly

**Comment by lewismcgeary** [comment]
Trousers pixelly

**Comment by lewismcgeary** [comment]
Snow transparentish centre looks weird when expanded with bright green background

**Comment by lewismcgeary** [comment]
Star - flat top of image has a little bump on it

**Comment by lewismcgeary** [comment]
Motorbike - weird transparency

**Comment by lewismcgeary** [comment]
Bus pixelly

**Comment by derwinmcgeary** [comment]
Done down to here with the exception of "Hand/fingers Foot/toes" which is a more conceptual problem, which means a really big shell script

**Comment by derwinmcgeary** [comment]
All is shiny.
