### ISSUE TITLE
Tagline and description

### ISSUE THREAD

**Issue by derwinmcgeary** [lewismcgeary/VocabBuilder#87]

**Comment by lewismcgeary** [comment]
Points to hit
-designed with babies/toddlers in mind, large images to press, audio/visual feedback
-no ads
-simple, the only words are the ones your child is learning
-no internet connection needed
-no in-app purchases

**Comment by lewismcgeary** [comment]
include (approximate?) number of words

**Comment by lewismcgeary** [comment]
improve English and Russian versions

**Comment by derwinmcgeary** [comment]
Looks OK
