### ISSUE TITLE
reinforcement of words

### ISSUE THREAD

**Issue by lewismcgeary** [lewismcgeary/VocabBuilder#97]
Repetition of words, possibilities:
-after correct answer selected, repeat word as part of success screen
-play word twice in question, when word is sole item on screen, and again when pictures pop up
-all words recap at end of quiz

**Comment by lewismcgeary** [comment]
word now repeats when correct answer selected

**Comment by derwinmcgeary** [comment]
Working perfectly!
<pause>
Working perfectly!
Yay!
